insert into tb_exame(id_exame, nm_exame, id_categoria) values
(1, 'Abdome Total', 1),
(2, 'Venoso de Membro Superior Direito', 1),
(3, 'Mamária',2),
(4, 'Pévilca (via transvaginal)', 2),
(5, 'Morfológica de 1ºTrimestre', 3),
(6, 'Gestacional 5D', 3),
(7, 'Ecodopplercardiograma', 4),
(8, 'Teste Ergometrico', 4),
(9, 'Mamografia Convencional', 5),
(10, 'Mamografia Digital', 5),
(11, 'Punção de Tireóide', 6),
(12, 'Densitometria Óssea', 7),
(13, 'Bacia', 8),
(14, 'Torax', 8),
(15, 'Coxas', 9),
(16, 'Colangioressonancia', 9),
(17, 'Cranio', 10),
(18, 'Pescoço', 10);